!     -*- f90 -*-
!     This file is autogenerated with f2py (version:2)
!     It contains Fortran 90 wrappers to fortran functions.

      subroutine f2py_f2pytest_getdims_a(r,s,f2pysetdata,flag)
      use f2pytest, only: d => a

      integer flag
      external f2pysetdata
      logical ns
      integer r,i,j
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1),s(2)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_f2pytest_getdims_a
      
      subroutine f2pyinitf2pytest(f2pysetupfunc)
      use f2pytest, only : a
      use f2pytest, only : allocate_a
      use f2pytest, only : print_a
      external f2pysetupfunc
      external f2py_f2pytest_getdims_a
      call f2pysetupfunc(f2py_f2pytest_getdims_a,allocate_a,print_a)
      end subroutine f2pyinitf2pytest


